{% set version = "1.9.19" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tmb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TMB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TMB/TMB_{{ version }}.tar.gz
  sha256: 379d6ea602c3b2691bfd03c59f6310e083fb9d50d6d4550606d5b0d674f2f8bf

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}    # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
  host:
    - libblas
    - liblapack
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
    - r-base
    - r-matrix >=1.0_12
    - r-rcppeigen
  run:
    - r-base
    - r-matrix >=1.0_12
    - r-rcppeigen

test:
  commands:
    - $R -e "library('TMB')"           # [not win]
    - "\"%R%\" -e \"library('TMB')\""  # [win]

about:
  home: http://tmb-project.org
  license: GPL-2.0-only
  summary: "With this tool, a user should be able to quickly implement complex random effect models through simple C++ templates. The package combines 'CppAD' (C++ automatic differentiation), 'Eigen' (templated matrix-vector library) and 'CHOLMOD' (sparse matrix routines available from R) to obtain an efficient implementation
    of the applied Laplace approximation with exact derivatives. Key features are: Automatic sparseness detection, parallelism through 'BLAS' and parallel user templates."
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
